# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/hicksze1/Pluto-PYNQ/hdl/projects/common/xilinx/adi_fir_filter_constr.xdc

# XDC: /home/hicksze1/Pluto-PYNQ/Pluto/base/system/system_constr.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_0/system_sys_concat_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0 || ORIG_REF_NAME==system_sys_concat_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_spi_0/system_axi_spi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_spi_0 || ORIG_REF_NAME==system_axi_spi_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_iic_main_0 || ORIG_REF_NAME==system_axi_iic_main_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_cdc_sync_active_0/system_cdc_sync_active_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cdc_sync_active_0 || ORIG_REF_NAME==system_cdc_sync_active_0} -quiet] -quiet

# IP: bd/system/ip/system_rate_gen_0/system_rate_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rate_gen_0 || ORIG_REF_NAME==system_rate_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_0_0/system_fir_interpolation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_interpolation_0_0 || ORIG_REF_NAME==system_fir_interpolation_0_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_0_0/system_logic_and_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_logic_and_0_0 || ORIG_REF_NAME==system_logic_and_0_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_0_0/system_out_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_out_mux_0_0 || ORIG_REF_NAME==system_out_mux_0_0} -quiet] -quiet

# IP: bd/system/ip/system_fir_interpolation_1_0/system_fir_interpolation_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_interpolation_1_0 || ORIG_REF_NAME==system_fir_interpolation_1_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_and_1_0/system_logic_and_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_logic_and_1_0 || ORIG_REF_NAME==system_logic_and_1_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_1_0/system_out_mux_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_out_mux_1_0 || ORIG_REF_NAME==system_out_mux_1_0} -quiet] -quiet

# IP: bd/system/ip/system_VCC_1_0/system_VCC_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_VCC_1_0 || ORIG_REF_NAME==system_VCC_1_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_32_0/system_GND_32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_32_0 || ORIG_REF_NAME==system_GND_32_0} -quiet] -quiet

# IP: bd/system/ip/system_interp_slice_0/system_interp_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_interp_slice_0 || ORIG_REF_NAME==system_interp_slice_0} -quiet] -quiet

# IP: bd/system/ip/system_tx_upack_0/system_tx_upack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_tx_upack_0 || ORIG_REF_NAME==system_tx_upack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_cdc_sync_active_1/system_cdc_sync_active_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cdc_sync_active_1 || ORIG_REF_NAME==system_cdc_sync_active_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_0_0/system_fir_decimation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_decimation_0_0 || ORIG_REF_NAME==system_fir_decimation_0_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_0_1/system_out_mux_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_out_mux_0_1 || ORIG_REF_NAME==system_out_mux_0_1} -quiet] -quiet

# IP: bd/system/ip/system_fir_decimation_1_0/system_fir_decimation_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fir_decimation_1_0 || ORIG_REF_NAME==system_fir_decimation_1_0} -quiet] -quiet

# IP: bd/system/ip/system_out_mux_1_1/system_out_mux_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_out_mux_1_1 || ORIG_REF_NAME==system_out_mux_1_1} -quiet] -quiet

# IP: bd/system/ip/system_decim_slice_0/system_decim_slice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_decim_slice_0 || ORIG_REF_NAME==system_decim_slice_0} -quiet] -quiet

# IP: bd/system/ip/system_cpack_0/system_cpack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cpack_0 || ORIG_REF_NAME==system_cpack_0} -quiet] -quiet

# IP: bd/system/ip/system_logic_or_0/system_logic_or_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_logic_or_0 || ORIG_REF_NAME==system_logic_or_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: /home/hicksze1/Pluto-PYNQ/Pluto/base/system/pluto.gen/sources_1/bd/system/system_ooc.xdc
